### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by mp1pro** [amanda-ayala/warby-funnels-aayala#1]
Criteria 1: Report

    Score Level: 4/4 (Exceeds Expectations)
    Comment(s): Every answer has three components: 1) SQL queries, 2) output tables as evidence, 3) text interpreting the query results. Each report was very thorough and practical. 

Criteria 2: Query Accuracy

    Score Level: 4/4 (Exceeds Expectations)
    Comment(s): All queries accurately retrieve the data intended. 

Criteria 3: Query Formatting

    Score Level: 4/4 (Exceeds Expectations)
    Comment(s): Queries adhere to at the rules of the style guide. 

Criteria 4: Understanding underlying concepts and terminology

    Score Level: 3/4 (Exceeds Expectations)
    Comment(s): Report demonstrates an above-and-beyond understanding of the dataset. It shows how all components of the data and how they link together. Really appreciated the commentary and comparisons given for each question. My only suggestion would be to add a final conclusion which makes suggestions on how to improve sales. 

Overall Score: 15/16

**Comment by amanda-ayala** [comment]
Thank you @mp1pro !

I had considered making improvement suggestions but wasn't sure whether it was necessary, so I appreciate the suggestion and will add some ideas at the end.

Close #1
